### Intro to numpy

Numpy es una librería para utilizar matrices y tensores en python de modo más eficiente que utilizando listas de listas.
  * Define todas las operaciones con matrices, vectores y escalares; en ese sentido se asemeja a matlab. Por ello no tendremos que hacer un doble for para multipliacar dos matrices, sino que directamente haremos A*B.
  * Internamente está implementada en C, por lo que es muy eficiente.
  * El inconveniente es que las dimensiones de una matriz son fijas en memoria.
  * Implementa todas las funciones matemáticas clásicas para aplicarlas a cada elemento de una matriz o tensor.
  * Es capaz de aplicar operaciones a tesores computestos de matrices, muy útil al trabajar con redes de neuronas.

Tutorial: https://www.tutorialspoint.com/numpy/index.htm

Manual: https://docs.scipy.org/doc/numpy/index.html

Intro to markdown: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

In [5]:
# para mostrar todas las salidas y no sólo la última

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [6]:
# importación y creación a partir de listas de listas

import numpy as np # importa numpy

a = np.array([[1, 2, 3], [4, 5, 6]]) # crea un array de numpy a partir de una lista de python

a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# podemos en cualquier momento convertir un array de numpy en lista de nuevo

a.tolist()

[[1, 2, 3], [4, 5, 6]]

In [8]:
# cortar columnas y subarrays

b = a[:,0] # corta primera columna, pero como vector fila a[i][j]
b

c = a[:,[0]] # corta primera columna, pero como vector columna
c

array([1, 4])

array([[1],
       [4]])

In [9]:
# componer nuevos arrays a partir de partes de los ya existentes

np.hstack((c, a, c))

array([[1, 1, 2, 3, 1],
       [4, 4, 5, 6, 4]])

In [10]:
# operaciones con matrices

np.transpose(a) # transpone matriz, también con .T
a

np.dot(a,np.transpose(a))

array([[1, 4],
       [2, 5],
       [3, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

array([[14, 32],
       [32, 77]])

In [46]:
# hay varias maneras de hacer las cosas
# con notación funcional o con infija

a.T # transpone

a @ a.T # @ es el producto de matrices


array([[1, 4],
       [2, 5],
       [3, 6]])

array([[14, 32],
       [32, 77]])

In [47]:
# el producto escalar se haría multiplicando componente a componente y sumando todo

c = np.array([1, 2, 3])
np.sum(c * c)

# y el producto de un número por una matriz

5 * c

a = np.array([[1, 2, 3], [4, 5, 6]]) # crea un array de numpy a partir de una lista de python
c2 = np.array([[1, 2]])

np.shape(c2)
np.shape(a)

c2 @ a # es producto matricial, la salida tendrá dimensión (1,3)

# * es producto componente a componente con broadcast, cuando los elementos se acaban vuelve al principio
# sólo da error si no casa (quedan elementos sin utilizar)
c * a # ok

c2 * a # daría error

14

array([ 5, 10, 15])

(1, 2)

(2, 3)

array([[ 9, 12, 15]])

array([[ 1,  4,  9],
       [ 4, 10, 18]])

ValueError: operands could not be broadcast together with shapes (1,2) (2,3) 

In [13]:
# Carga de ficheros de datos
X = np.loadtxt('samples/iris.csv',dtype = 'float64',usecols = [0,1,2,3])
L = np.loadtxt('samples/iris.csv',dtype = str,usecols = [4]) 

d = []
options = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
for e in L:
    d.append(options.index(e))

X
L
d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [14]:
# Una cosa importante de numpy es que todas sus operaciones definidas sobre escalares funcionan también sobre vectores y matrices

def sigm (neta): # función sigmoidal
        return 1.0 / (1.0 + np.exp(-neta))

sigm(1.0)

v = np.array([0.0, 0.5, 1.0])
sigm(v)

# pero, ojo, no funcionaría sobre una lista; tiene que ser un array de numpy

0.7310585786300049

array([0.5       , 0.62245933, 0.73105858])

In [15]:
# números aleatorios

np.random.rand(5,5)*0.2-0.1

array([[ 0.03178155,  0.02999999, -0.04285269, -0.07688105, -0.04758164],
       [-0.05502002, -0.03962439,  0.06271423, -0.00197983,  0.04379722],
       [ 0.01850168,  0.05266471,  0.08895067,  0.02956739,  0.03707085],
       [ 0.07913238,  0.05043538,  0.0984548 , -0.07165474, -0.08382626],
       [ 0.02094769,  0.04170789,  0.04606709,  0.07242588, -0.06679652]])

In [16]:
# obtener y cambiar las dimensiones de una matriz (se usa mucho en redes de neuronas)

a
np.shape(a)

array([[1, 2, 3],
       [4, 5, 6]])

(2, 3)

In [17]:
a.reshape(3,2) # ojo, no es lo mismo que transponer

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
a = a.reshape(6,1)
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [19]:
# convertir un array en un vector
# es útil para convertir arrays unidimensionales en vectores y no preocuparnos por sus dimensiones, 
# ya que podemos multiplicar siempre vectores por matrices si el bnúmero de elementos es correcto (broadcasting)
# además, el resultado de una matriz por un vector es siempre un vector

v = a.flatten()
v

m = np.random.rand(6,2)
m

v.dot(m)

m.transpose().dot(v)


array([1, 2, 3, 4, 5, 6])

array([[0.53233902, 0.2840504 ],
       [0.66913353, 0.92376622],
       [0.13939141, 0.95991888],
       [0.08545912, 0.6468232 ],
       [0.84356543, 0.5942084 ],
       [0.01443106, 0.44605329]])

array([ 6.93503033, 13.24599401])

array([ 6.93503033, 13.24599401])

In [20]:
# otra cuestión interesante es que dot puede usarse como operando o como método

np.dot(v,m)

# equivale a

v.dot(m)

# la ventaja de la primera forma es que puede usarse con listas de python además de con estructuras de numpy

np.dot([1, 2, 3, 4, 5, 6],m)

np.dot([1, 2],[[1, 1, 1],[2, 3, 4]])



array([ 6.93503033, 13.24599401])

array([ 6.93503033, 13.24599401])

array([ 6.93503033, 13.24599401])

array([5, 7, 9])

In [21]:
# como hemos visto, cualquier función se puede aplicar sobre escalares o tensores

np.sin(v)
np.sin(m)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

array([[0.50755008, 0.28024603],
       [0.6203066 , 0.79787763],
       [0.13894045, 0.81914504],
       [0.08535513, 0.60265436],
       [0.74701818, 0.55985302],
       [0.01443056, 0.43140835]])

In [22]:
# por tanto, si queremos propagar por un peceptrón, ¿cómo se haría?
# perceptrón con 2 entradas y 1 salida (ejemplo OR)
# np.shape(e)=(1,2); np.shape(W)=(2,1); np.shape(neta)=(1,1); np.shape(b)=(1,1)

e = np.array([1, 0])

W = np.random.rand(2, 1) - 0.5
b = np.random.rand(1) - 0.5

print('entrada',e)
print('pesos',W)
print('bias',b)

neta = e@W + b
print('entrada neta',neta)

s1 = sigm(neta)
print('salida (sigmoidal)',s1)

s2 = np.heaviside(neta, 0)
print('salida (escalón)',s2)

entrada [1 0]
pesos [[0.27731678]
 [0.37915753]]
bias [0.39882199]
entrada neta [0.67613877]
salida (sigmoidal) [0.66287637]
salida (escalón) [1.]


In [41]:
# otro modo de hacerlo es con where
# where aplica una función booleana a cada elemento de un tensor, y devuelve el segundo argumentos si se cumple
# y el tercero si no se cumple

s = np.where(neta>0,1,0)
s

array([1])

In [40]:
# y una característica muy importante de numpy es que si una operación se aplica a un tensor con más dimensiones
# de la cuenta, la primera dimensión se utiliza como lista y se devuelve una lista con todos los resultados
# eso permite usar el primer índice para identificar los ejemplos de entrenamiento y la operación de propagación
# se hace de golpe
import random

e = np.array([1, 2, 3])
w = np.random.random((3, 2))

print(e@w) # da un vector de salidas

# pero si tenemos todos los ejemplos en un array
e = np.array([[1, 2, 3], [4, 5, 6]])

print(e@w) # da una lista de salidas



[2.86835584 3.43424099]
[[2.86835584 3.43424099]
 [7.04423849 7.70385802]]
